project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: images/cafe.png
  navbar:
    background: primary
    foreground: secondary
    logo: images/cafe.png
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
    right:
        - icon: linkedin
          href: https://www.linkedin.com/in/rayyan-shekhani/
        - icon: github
          href: https://github.com/orchuk12
format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true



