project:
  type: website
  output-dir: docs

website:
  title: "Rayyan Aamir"
  favicon: images/cafe.png
  navbar:
    background: primary
    foreground: secondary
    logo: images/cafe.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
        - icon: linkedin
          href: https://www.linkedin.com/in/rayyan-shekhani/
        - icon: github
          href: https://github.com/orchuk12
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



