project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Rayyan Aamir Shekhani"
  favicon: images/logo_1.png
  navbar:
    background: primary
    foreground: secondary
    logo: images/logo_1.png
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: projects/index.qmd
        text: Projects
    right:
        - icon: linkedin
          href: https://www.linkedin.com/in/rayyan-shekhani/
        - icon: github
          href: https://github.com/orchuk12
format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true



