---
title: "Curriculum Vitae"
format: 
  html:
    page-layout: full
css: ../styles.css
---

## Education 

<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Master of Business Analytics**</td>
    <td style="text-align:right;">2024 -- 2025</td>
  </tr>
  <tr>
    <td style="text-align:left;">Monash University -- Melbourne, Australia</td>
  </tr>
  <tr>
    <td style="text-align:left;"> Grade: (3.8/4.0 CGPA)</td>
  </tr>
</table>


<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Bachelor of Business and Commerce**</td>
    <td style="text-align:right;">2020 -- 2023</td>
  </tr>
  <tr>
    <td style="text-align:left;">Major: Business Analytics</td>
  </tr>
  <tr>
    <td style="text-align:left;">Monash University -- Kuala Lumpur, Malaysia</td>
  </tr>
  <tr>
    <td style="text-align:left;"> Grade: (3.2/4.0 CGPA)</td>
  </tr>
</table>

## Skills

<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Software**</td>
  </tr>
  <tr>
    <td style="text-align:left;">RStudio, Git, Tableau, Power BI, Oracle Data Modeler, MongoDB, 
    SAS EM, Canva</td>
  </tr>

  <tr>
    <td style="text-align:left;">**Languages**</td>
  </tr>
  <tr>
    <td style="text-align:left;">R, HTML, css, SQL</td>
  </tr>
  
  <tr>
    <td style="text-align:left;">**Cloud**</td>
  </tr>
  <tr>
    <td style="text-align:left;">AWS</td>
  </tr>
</table>

## Projects

<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Data Visualization Dashboard Using Rshiny**</td>
    <td style="text-align:right;">June 2024</td>
  </tr>
</table>

- Produced a data visualization project to outline key migration statistics impacting Australia’s labour force, wholly implemented the dashboard using Rshiny.
- Extensive data cleaning and wrangling performed through tidyverse and relevant packages. Utilized leaflet and geosphere package for geographical mapping and coordinate handling.

<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**SAS EM Data Mining, Clustering, and Segmentation**</td>
    <td style="text-align:right;">February 2023</td>
  </tr>
</table>

- Utilizing the necessary data curation skills to produce, examine, and execute a rational research question.
- Using SAS Enterprise Miner to generate clustering and segmentation profiles and based on the client’s requests regarding result insights
- Assessments were conducted using Logistic Regression Models, Neural Network Models, Decision Tree Models, and Ensemble Models.

<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Forecasting and Machine Learning Using R**</td>
    <td style="text-align:right;">November 2023</td>
  </tr>
</table>

- Performing forecasting, time series regression, decomposition, and machine learning techniques to determine post-Covid profitability of air travel in the United States.
- Various simple forecasting methods, ETS models, and ARIMA models were utilized to suit both stationary and non-stationary data segments.
- Forecasting and machine learning was performed using R-Studio, whilst data visualization and further analysis was performed using Tableau.

<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Optimization in MS Excel**</td>
    <td style="text-align:right;">March 2022</td>
  </tr>
</table>

- Using solver within MS Excel to solve a client’s problem using Linear Programming to evaluate data sensitivity with the Simplex Method. Utilizing Primal/Dual Models to supplement Transportation-based obstacles.
- Utilizing and selecting the best-of-rest method from Greedy, Northwest, and Vogel’s Approximation Method (VAM).
- The mentioned methods were used in order to determine whether the maximization of material production was necessary and cost-efficient.

## Experience

<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Online Personal Shopperr**</td>
  </tr>
  <tr>
    <td style="text-align:left;">Woolworths Supermarket -- Hawthorn East, 3123, VIC, Australia</td>
    <td style="text-align:right;">November 2024 -- Present</td>
  </tr>
</table>

- Systematically prepare and fulfill online orders to ensure an excellent customer shopping experience.
- Assist with in-store customer service, addressing inquiries and providing support.
- Contribute to restocking and stocktaking to maintain efficient inventory management.

<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Front End Assistant**</td>
  </tr>
  <tr>
    <td style="text-align:left;">Costco Wholesale -- Moorabbin, 3194, VIC, Australia</td>
    <td style="text-align:right;">November 2024 -- Present</td>
  </tr>
</table>

- Operate checkouts and verify customer memberships to ensure smooth transactions.
- Assist customers with inquiries and provide guidance around the store.
- Collect and organize trolleys to maintain a safe and efficient shopping environment.

<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Team Member**</td>
  </tr>
  <tr>
    <td style="text-align:left;">Glenny Kebabs -- Glen Waverley, 3150, VIC, Australia</td>
    <td style="text-align:right;">August 2024 -- Present</td>
  </tr>
</table>

- Assisted with kitchen operations, including packaging and delivering orders efficiently to meet customer demands.
- Provided exceptional customer service by taking orders, addressing complaints, and ensuring a positive dining experience.
- Managed inventory levels and reported to the supervisor for replenishment, ensuring smooth kitchen operations.



<table style="width:100%;">
  <tr>
    <td style="text-align:left;">**Operations Lead**</td>
  </tr>
  <tr>
    <td style="text-align:left;">Monash University Student Association -- Kuala Lumpur, 
    Malaysia</td>
    <td style="text-align:right;">November 2020 -- June 2021</td>
  </tr>
</table>

- Take leadership in logistics handling of upcoming events whilst working closely with the Treasurer and President of the faculty to discuss budgets and other necessary details.
- Conducting analysis between participation rates and event outcomes to utilize budgets and tactics efficiently to maximize output.
- Initiating event plans, executing, and leadership to ensure high-participation rates between host and attendee. 

